# Generated by Django 5.0.3 on 2024-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='answer',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answer9',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
    ]
