# Generated by Django 4.2.14 on 2024-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("with", "0005_alter_surveyresponse_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
