# Generated by Django 5.0.3 on 2024-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with', '0006_myuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='unknown', max_length=255, null=True),
        ),
    ]
